version: "3"

services:
  db:
    container_name: Tryitter_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/x86_64
    restart: always
    ports:
      - 1433:1433

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@2022
      # - MSSQL_PID=Developer

networks:
  default:
    name: Tryitter_net